### ISSUE TITLE
app crashed --harmony_default_parameters

### ISSUE THREAD

**Issue by SpiesInOrbit** [coreyp1/defiant#1]
Just trying to get it up and running. Maybe a node version issue.
```
node: bad option: --harmony_default_parameters
[nodemon] app crashed - waiting for file changes before starting...

```
Thanks

**Comment by coreyp1** [comment]
Indeed.  Node 7.x removed some of the harmony flags (that is, the features are now supported by default and are no longer experimental).

I have removed the flags from the npm and nodemon config files.

Thanks for looking at this btw, but be forewarned that it's *very* rough, and completely non-functional.  It's still very much a sandbox.  I'm working on the ORM part of it at the moment.  Hit me up on Skype if you want me to tell you about it in more detail.
