### ISSUE TITLE
What's the difference with a container orchestrator like docker-compose?

### ISSUE THREAD

**Issue by motet-a** [coreyp1/defiant#2]
It is written in the README that Defiant can orchestrate independant and individual systems. However, docker-compose (and many others) does that. Could you clarify it?

Thanks.

**Comment by coreyp1** [comment]
Defiant is a framework (and a very nascent one, at that!).  The statement that you are referring to is meant to demonstrate potential use cases for Defiant.

As you have observed, Docker already does orchestrate independant systems, and it does a good job at it.  Defiant, on the other hand, could serve as an interface between Docker and the user (perhaps providing a web-based frontend or mobile api) for controlling and monitoring the Docker instances.  I am not claiming that this type of system is currently built, but that rather it is a use case that would be interesting to build on Defiant.
